// import './class/letAndConst'
// import './class/lesson-2'
// import './class/lesson-3'

// 兼容库，String中的一些方法
// import 'babel-polyfill'
// import './class/lesson-3String'
// import './class/lesson-4'
// import './class/lesson-5'
// import './class/lesson-6'
// import './class/lesson-7'
// import './class/lesson-8'
// import './class/lesson-9SetAndMap'
// import './class/lesson-10'
// import './class/lesson-11'
// import './class/lesson-12'
// import './class/lesson-13'
import './class/lesson-14'